### PR TITLE
Release gravity compensation from CUHK

### PR DESCRIPTION
**Pull request by vincent-hui**

### CODE REVIEW

**Comment by zchen24** [comment]
@vincent-hui @linhongbin Is this PR ready for review? Thanks.

**Comment by adeguet1** [comment]
To all, I ran into some hardware issues last week and couldn’t test the branch.  I should be able to test the code early this week and send some feedback.

**Comment by linhongbin** [comment]
Hi all, I push a new version for matlab  codes of dvrk GC. Since the time we push the fisrt version, we have improved our method to achieve a more stable and reproducible gravity compensation process. The 2nd version is not compatible with the 1st one. So after you pull from the remote, you might need to rerun all the process by calling:

 [GC_controllers,output_data_struct] =  gc_demo('MTML&MTMR')

If you have done data collection using 1st version, the data folder should be decapitated. 

For separated testing, you might need to run(takes MTML for example):
For datacollection:
[is_dataCollection_finish, output_data_struct] = dataCollection('MTML', 'dataCollection_config.json');

For estimation:
[is_MTM_lse_finish, output_dynamic_matrix, output_lse_config] = MLSE('MTML', 'MLSE_config.json', './../GC_Data_stable_test')

For GC_controllers:
[is_test_pass,GC_Controllers] = GC_controller('MTML','GC_controller_config.json','./../GC_Data_stable_test','4POL',9.81)

The whole data collection process might takes around 1 hour for each arm.

Looking forward for news of review.

**Comment by adeguet1** [comment]
Just to confirm, this PR is now obsolete and the update code can be found at https://github.com/jhu-dvrk/dvrk-gravity-compensation

@vincent-hui , @linhongbin , can we close this PR?

**Comment by vincent-hui** [comment]
yes, we can close this PR.

**Pull request closed without merging**
